### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by ihmunro** [ashfurrow/UICollectionViewExample#1]
Hi There

I followed your tutorial, but no where does it say anything about 
# import <PXAPI/PXAPI.h>

Where are the files for this ?

Iain

**Comment by ashfurrow** [comment]
Hi,

In the `UICollectionView` example, I didn't go into a lot of detail about setting up the [500px iOS SDK](https://github.com/500px/500px-iOS-api). You need to go there and follow the `README` for instructions on how to set up the project - it's very straightforward. 

In _this_ example (on GitHub), I've `#import`ed the necessary file in `UICollectionViewExample-Prefix.pch` so that it is included in every file.

I hope that clears things up - please don't hesitate to let me know if you have any other feedback.

Ash
